### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by wpdonders** [dbis-ilm/grizzly#3]
Hi there,

I'm interested in the concept of writing pandas-like API to generate SQL to talk to relational databases. I was wondering if this project is currently no longer maintained.

Thanks!

**Comment by elidhu** [comment]
Hi @wpdonders, I am not a maintainer, just a fellow enthusiast. You might be interested in checking out [ibis](https://github.com/ibis-project/ibis).

**Comment by wpdonders** [comment]
Thanks @kevinglasson !

**Comment by hag0r** [comment]
Hi, Grizzly is not unmaintained, but we're using our internal Git for development and will probably sync again soon. If you have any specific requests or questions I am glad to help! :)
